### PR TITLE
winit-x11: fix debug mode overflow panic in `set_timestamp`

### LINKED ISSUE #4484: X11 panic: attempt to subtract with overflow
### Description

I randomly got this panic after closing my app:

```
thread 'main' (3642714) panicked at /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/winit-0.30.12/src/platform_impl/linux/x11/xdisplay.rs:237:77:
attempt to subtract with overflow
```

https://docs.rs/crate/winit/latest/source/src/platform_impl/linux/x11/xdisplay.rs#237

### OS and window mananger

Linux Ubuntu 24.04.3 LTS

### Winit version

0.30.12

### PR DESCRIPTION
**Pull request by SuchAFuriousDeath**
Fixes #4484

- [ ] Tested on all platforms changed
- [ ] Added an entry to the `changelog` module if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

### CODE REVIEW

File: winit-x11/src/xdisplay.rs [hunk 1]
```diff
@@ -250,7 +250,8 @@ impl XConnection {
         // Store the timestamp in the slot if it's greater than the last one.
         let mut last_timestamp = self.timestamp.load(Ordering::Relaxed);
         loop {
-            let wrapping_sub = |a: xproto::Timestamp, b: xproto::Timestamp| (a as i32) - (b as i32);
```
Comment (kchibisov) [inline winit-x11/src/xdisplay.rs:253]: Can you inline closure body at the place it's being used while at it?

**Comment by SuchAFuriousDeath** [comment]
> Can you add changelog entry for that?

Sure, I didn't think it was worthy of one.

**Comment by kchibisov** [comment]
>Sure, I didn't think it was worthy of one.

If there's a bug report, then it's better to add one.

**Comment by SuchAFuriousDeath** [comment]
@kchibisov Are all issues in https://github.com/rust-windowing/winit/milestone/18 blockers for v0.31? Is there anyhing I could help with? I'd really like to make use of https://github.com/rust-windowing/winit/pull/3758 in Ruffle.
