### PR TITLE
Fix several crashes on Windows by heavily simplifying the event loop code

### LINKED ISSUE #1391: [Windows] thread 'main' panicked at 'redraw event in non-redraw phase'
Hi,

I am seeing this panic when resizing a window (on Windows 10) using master.
I am not seeing it when using winit 0.20.0.

The event loop does mostly nothing and does not invoke window.request_redraw().

```
thread 'main' panicked at 'redraw event in non-redraw phase', C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop\runner.rs:427:17
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:76
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:60
   3: core::fmt::write
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libcore\fmt\mod.rs:1030
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:64
   6: std::sys_common::backtrace::print
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:196
   8: std::panicking::default_hook
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:210
   9: std::panicking::rust_panic_with_hook
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:473
  10: std::panicking::begin_panic<str*>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\panicking.rs:407
  11: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop\runner.rs:427
  12: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event_unbuffered<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop\runner.rs:161
  13: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop\runner.rs:150
  14: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:104
  15: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:680
  16: DefSubclassProc
  17: DefSubclassProc
  18: DispatchMessageW
  19: DispatchMessageW
  20: GetSystemMetrics
  21: KiUserCallbackDispatcher
  22: NtUserMessageCall
  23: GetWindowTextW
  24: GetWindowTextW
  25: GetThemeAppProperties
  26: GetThemeAppProperties
  27: Ordinal119
  28: Ordinal119
  29: GetWindowTextW
  30: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:826
  31: DefSubclassProc
  32: DefSubclassProc
  33: DispatchMessageW
  34: DispatchMessageW
  35: GetSystemMetrics
  36: KiUserCallbackDispatcher
  37: NtUserMessageCall
  38: GetWindowTextW
  39: GetWindowTextW
  40: GetThemeAppProperties
  41: GetThemeAppProperties
  42: Ordinal119
  43: Ordinal119
  44: GetWindowTextW
  45: DispatchMessageW
  46: CallWindowProcW
  47: DefSubclassProc
  48: DefSubclassProc
  49: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:653
  50: DefSubclassProc
  51: DefSubclassProc
  52: DispatchMessageW
  53: DispatchMessageW
  54: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:235
  55: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\msys64\home\Philippe\rust\winit\src\platform_impl\windows\event_loop.rs:192
  56: winit::event_loop::EventLoop<()>::run<(),closure-0>
             at C:\msys64\home\Philippe\rust\winit\src\event_loop.rs:151
  57: winit_gameloop::game_loop::GameLoop::run<closure-0,closure-1,closure-2>
             at .\src\game_loop.rs:52
  58: simple::main
             at .\examples\src\bin\simple.rs:18
  59: std::rt::lang_start::{{closure}}<()>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\rt.rs:64
  60: std::rt::lang_start_internal::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:49
  61: std::panicking::try::do_call<closure-0,i32>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:292
  62: panic_unwind::__rust_maybe_catch_panic
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libpanic_unwind\lib.rs:80
  63: std::panicking::try
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:271
  64: std::panic::catch_unwind
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panic.rs:394
  65: std::rt::lang_start_internal
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:48
  66: std::rt::lang_start<()>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\rt.rs:64
  67: main
  68: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  69: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  70: BaseThreadInitThunk
  71: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\simple.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

### LINKED ISSUE #1400: [Windows] Not possible to create multiple windows (thread 'main' panicked at 'already mutably borrowed')
Hi 🙂 

Since https://github.com/rust-windowing/winit/commit/6a330a2894873d29fbbfdeebfc1a215577213996 it is not possible to create multiple windows on Windows (10). It can be reproduced with `multiwindow` example. The single `window` example works fine though.

```
PS C:\Users\tester\Documents\GitHub\winit> $ENV:RUST_BACKTRACE = "full"
PS C:\Users\tester\Documents\GitHub\winit> cargo run --example multiwindow
```

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `target\debug\examples\multiwindow.exe`
thread 'main' panicked at 'already mutably borrowed: BorrowError', src\libcore\result.rs:1165:5
stack backtrace:
   0:     0x7ff6b2f461c9 - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace\mod.rs:66
   1:     0x7ff6b2f461c9 - std::sys_common::backtrace::_print_fmt
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:76   2:     0x7ff6b2f461c9 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:60   3:     0x7ff6b2f5adfb - core::fmt::write
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libcore\fmt\mod.rs:1030
   4:     0x7ff6b2f433a4 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\io\mod.rs:1412
   5:     0x7ff6b2f48960 - std::sys_common::backtrace::_print
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:64   6:     0x7ff6b2f48960 - std::sys_common::backtrace::print
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:49   7:     0x7ff6b2f48960 - std::panicking::default_hook::{{closure}}
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:196
   8:     0x7ff6b2f4858a - std::panicking::default_hook
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:210
   9:     0x7ff6b2f491b8 - std::panicking::rust_panic_with_hook
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:473
  10:     0x7ff6b2f48d24 - std::panicking::continue_panic_fmt
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:380
  11:     0x7ff6b2f48c09 - std::panicking::rust_begin_panic
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:307
  12:     0x7ff6b2f57469 - core::panicking::panic_fmt
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libcore\panicking.rs:85
  13:     0x7ff6b2f5756f - core::result::unwrap_failed
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libcore\result.rs:1165
  14:     0x7ff6b2f02aaf - core::result::Result<core::cell::Ref<core::option::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>, core::cell::BorrowError>::expect<core::cell::Ref<core::option::Option<winit::platform_impl::platform::event_loop::runner::
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libcore\result.rs:960
  15:     0x7ff6b2ef517c - core::cell::RefCell<core::option::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>::borrow<core::option::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libcore\cell.rs:788
  16:     0x7ff6b2ef8508 - winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop\runner.rs:133
  17:     0x7ff6b2e8196b - winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop.rs:104
  18:     0x7ff6b2e858ec - winit::platform_impl::platform::event_loop::public_window_callback<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop.rs:1367
  19:     0x7ffe8273b88a - DefSubclassProc
  20:     0x7ffe8273b745 - DefSubclassProc
  21:     0x7ffe97117446 - DispatchMessageW
  22:     0x7ffe9711716c - DispatchMessageW
  23:     0x7ffe97120a23 - EnumChildWindows
  24:     0x7ffe99ea3494 - KiUserCallbackDispatcher
  25:     0x7ffe96ed1184 - NtUserMessageCall
  26:     0x7ffe97114b16 - GetWindowTextW
  27:     0x7ffe97114488 - GetWindowTextW
  28:     0x7ffe97117446 - DispatchMessageW
  29:     0x7ffe9711716c - DispatchMessageW
  30:     0x7ffe97120a23 - EnumChildWindows
  31:     0x7ffe99ea3494 - KiUserCallbackDispatcher
  32:     0x7ffe96ed1b84 - NtUserShowWindow
  33:     0x7ff6b2efcf76 - winit::platform_impl::platform::window_state::WindowFlags::apply_diff
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\window_state.rs:245
  34:     0x7ff6b2e8052f - winit::platform_impl::platform::window_state::WindowState::set_window_flags<closure-0>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\window_state.rs:141
  35:     0x7ff6b2e7f722 - winit::platform_impl::platform::window::{{impl}}::set_visible::{{closure}}
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\window.rs:131
  36:     0x7ff6b2e87a1b - winit::platform_impl::platform::event_loop::EventLoopThreadExecutor::execute_in_thread<closure-0>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop.rs:420
  37:     0x7ff6b2e77491 - winit::platform_impl::platform::window::Window::set_visible
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\window.rs:130
  38:     0x7ff6b2e7ef68 - winit::platform_impl::platform::window::init<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\window.rs:779
  39:     0x7ff6b2e7f858 - winit::platform_impl::platform::window::Window::new<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\window.rs:72
  40:     0x7ff6b2e88014 - winit::window::WindowBuilder::build<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\window.rs:333
  41:     0x7ff6b2e8812a - winit::window::Window::new<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\window.rs:359
  42:     0x7ff6b2e72b6b - multiwindow::main::{{closure}}
                               at C:\Users\tester\Documents\GitHub\winit\examples\multiwindow.rs:42
  43:     0x7ff6b2e81834 - winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop.rs:207
  44:     0x7ff6b2f06923 - alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\liballoc\boxed.rs:929
  45:     0x7ff6b2efadc6 - winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop\runner.rs:563
  46:     0x7ff6b2f11896 - std::panic::{{impl}}::call_once<(),closure-0>
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\panic.rs:315
  47:     0x7ff6b2f25e02 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\panicking.rs:292
  48:     0x7ff6b2f4bcd2 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libpanic_unwind\lib.rs:80
  49:     0x7ff6b2f25c63 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\panicking.rs:271
  50:     0x7ff6b2f118d6 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\panic.rs:394
  51:     0x7ff6b2efab30 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop\runner.rs:561
  52:     0x7ff6b2efa091 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop\runner.rs:437
  53:     0x7ff6b2ef8d9b - winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event_unbuffered<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop\runner.rs:161
  54:     0x7ff6b2ef8831 - winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop\runner.rs:150
  55:     0x7ff6b2e8196b - winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop.rs:104
  56:     0x7ff6b2e83782 - winit::platform_impl::platform::event_loop::public_window_callback<()>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop.rs:940
  57:     0x7ffe8273b88a - DefSubclassProc
  58:     0x7ffe8273b745 - DefSubclassProc
  59:     0x7ffe97117446 - DispatchMessageW
  60:     0x7ffe97116f62 - DispatchMessageW
  61:     0x7ff6b2e813d8 - winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop.rs:235
  62:     0x7ff6b2e8189e - winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
                               at C:\Users\tester\Documents\GitHub\winit\src\platform_impl\windows\event_loop.rs:192
  63:     0x7ff6b2e88516 - winit::event_loop::EventLoop<()>::run<(),closure-0>
                               at C:\Users\tester\Documents\GitHub\winit\src\event_loop.rs:148
  64:     0x7ff6b2e890f5 - multiwindow::main
                               at C:\Users\tester\Documents\GitHub\winit\examples\multiwindow.rs:18
  65:     0x7ff6b2e7de40 - std::rt::lang_start::{{closure}}<()>
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\rt.rs:64
  66:     0x7ff6b2f48b67 - std::rt::lang_start_internal::{{closure}}
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:49
  67:     0x7ff6b2f48b67 - std::panicking::try::do_call<closure-0,i32>
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:292
  68:     0x7ff6b2f4bcd2 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libpanic_unwind\lib.rs:80
  69:     0x7ff6b2f494f2 - std::panicking::try
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:271
  70:     0x7ff6b2f494f2 - std::panic::catch_unwind
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panic.rs:394
  71:     0x7ff6b2f494f2 - std::rt::lang_start_internal
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:48
  72:     0x7ff6b2e7de1b - std::rt::lang_start<()>
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\rt.rs:64
  73:     0x7ff6b2e89280 - main
  74:     0x7ff6b2f5ed24 - invoke_main
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  75:     0x7ff6b2f5ed24 - __scrt_common_main_seh
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  76:     0x7ffe98827974 - BaseThreadInitThunk
  77:     0x7ffe99e6a271 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\examples\multiwindow.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

### LINKED ISSUE #1466: [Windows] calling request_redraw from thread triggers a panic
```
thread 'main' panicked at 'redraw event in non-redraw phase', src\platform_impl\windows\event_loop\runner.rs:427:17
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:84
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\fmt\mod.rs:1025
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:193
   8: std::panicking::default_hook
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:210
   9: std::panicking::rust_panic_with_hook
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:471
  10: std::panicking::begin_panic<str*>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\panicking.rs:404
  11: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::process_event<()>
             at .\src\platform_impl\windows\event_loop\runner.rs:427
  12: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event_unbuffered<()>
             at .\src\platform_impl\windows\event_loop\runner.rs:161
  13: winit::platform_impl::platform::event_loop::runner::ELRShared<()>::send_event<()>
             at .\src\platform_impl\windows\event_loop\runner.rs:150
  14: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
             at .\src\platform_impl\windows\event_loop.rs:104
  15: winit::platform_impl::platform::event_loop::public_window_callback<()>
             at .\src\platform_impl\windows\event_loop.rs:680
  16: DefSubclassProc
  17: DefSubclassProc
  18: CallWindowProcW
  19: DispatchMessageW
  20: IsWindowVisible
  21: KiUserCallbackDispatcher
  22: NtUserDispatchMessage
  23: DispatchMessageW
  24: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-1>
             at .\src\platform_impl\windows\event_loop.rs:254
  25: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-1>
             at .\src\platform_impl\windows\event_loop.rs:192
  26: winit::event_loop::EventLoop<()>::run<(),closure-1>
             at .\src\event_loop.rs:148
  27: control_flow::main
             at .\examples\control_flow.rs:55
  28: std::rt::lang_start::{{closure}}<()>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\rt.rs:67
  29: std::rt::lang_start_internal::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:52
  30: std::panicking::try::do_call<closure-0,i32>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:292
  31: panic_unwind::__rust_maybe_catch_panic
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libpanic_unwind\lib.rs:78
  32: std::panicking::try
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:270
  33: std::panic::catch_unwind
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panic.rs:394
  34: std::rt::lang_start_internal
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:51
  35: std::rt::lang_start<()>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\src\libstd\rt.rs:67
  36: main
  37: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  38: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  39: BaseThreadInitThunk
  40: RtlUserThreadStart
```

### LINKED ISSUE #1477: Calling `Window.redraw_window()` can cause the window to seemingly "destroy and recreate" itself intermittently on Windows 10
If my program calls `redraw_window()` inside the `MainEventsCleared` event and I hold my mouse still and don't use my keyboard, the window's decorations will briefly light up as if hovered over and then go back to normal. This happens intermittently. The window's task bar icon will also disappear and reappear at the same time the window decorations blink.

[Here](https://bittube.video/videos/watch/245fd88b-473c-4764-9f4e-592c4c279bd4) is a video demonstrating the bug.
The following is the code used in the video:
```Rust
use winit::{
    event::{DeviceEvent, ElementState, Event, KeyboardInput, VirtualKeyCode, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::WindowBuilder,
};

fn main() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new()
        .with_title("A Buggy Window")
        .build(&event_loop)
        .unwrap();
    let mut bug = false;
    event_loop.run(move |event, _, control_flow| match event {
        Event::WindowEvent {
            event: WindowEvent::CloseRequested,
            ..
        } => *control_flow = ControlFlow::Exit,
        Event::DeviceEvent {
            event:
                DeviceEvent::Key(KeyboardInput {
                    virtual_keycode: Some(VirtualKeyCode::B),
                    state: ElementState::Pressed,
                    ..
                }),
            ..
        } => {
            bug = !bug;
            if bug {
                println!("bug enabled");
            } else {
                println!("bug disabled");
            }
        }
        Event::MainEventsCleared => {
            if bug {
                window.request_redraw();
            }
        }
        _ => {}
    })
}
```
I've managed to get the bug to appear on both `winit = 0.21.0` and on the `master` branch (9999f53).

### PR DESCRIPTION
**Pull request by Osspial**
- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

I'll do a more detailed writeup on the rationale behind these changes when I'm more awake, but the TL;DR is that it drastically simplifies Winit's event loop model by always using the modal event loop. This PR's fixes are an alternate approach to the problems described in #1429 that simplifies the event model more than #1461 does, but it could not exist in its current form without @filnet's work and feedback in those threads.

Fixes #1477, fixes #1496.

### CODE REVIEW

**Comment by filnet** [comment]
Did some testing with the `control_flow` example.

When using `Wait` control flow and calling `request_redraw` from `MainEventsCleared`:
```
NewEvents(Init)
NewEvents(Init)
DeviceEvent { device_id: DeviceId(DeviceId(131227)), event: Added }
DeviceEvent { device_id: DeviceId(DeviceId(720955)), event: Added }
DeviceEvent { device_id: DeviceId(DeviceId(65599)), event: Added }
DeviceEvent { device_id: DeviceId(DeviceId(720957)), event: Added }
MainEventsCleared
[...]
NewEvents(WaitCancelled { start: Instant { t: 3125.514983921s }, requested_resume: None })
DeviceEvent { device_id: DeviceId(DeviceId(131227)), event: Motion { axis: 0, value: -1.0 } }
DeviceEvent { device_id: DeviceId(DeviceId(131227)), event: MouseMotion { delta: (-1.0, 0.0) } }
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { t: 3125.514983921s }, requested_resume: None })
MainEventsCleared
RedrawRequested(WindowId(WindowId(0x703d8)))
RedrawEventsCleared
```

Two issues:
- `NewEvents(Init)` is dispatched twice
- The last event loop (`MainEventsCleared` / `RedrawRequested` / `RedrawEventsCleared`) should not happen.

**Comment by filnet** [comment]
When using WaitUntil control flow only WaitCanceled gets emitted:

```
NewEvents(WaitCancelled { start: Instant { t: 5055.05687788s }, requested_resume: Some(Instant { t: 5060.765933731s }) })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { t: 5055.05687788s }, requested_resume: Some(Instant { t: 5060.866509712s }) })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { t: 5055.05687788s }, requested_resume: Some(Instant { t: 5060.967189259s }) })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { t: 5055.05687788s }, requested_resume: Some(Instant { t: 5061.067769905s }) })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { t: 5055.05687788s }, requested_resume: Some(Instant { t: 5061.168097083s }) })
MainEventsCleared
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { t: 5055.05687788s }, requested_resume: Some(Instant { t: 5061.268679596s }) })
MainEventsCleared
RedrawEventsCleared
```

**Comment by filnet** [comment]
When using Wait control flow and calling request_redraw from MainEventsCleared:

```
NewEvents(Poll)
MainEventsCleared
RedrawRequested(WindowId(WindowId(0xb0780)))
RedrawEventsCleared
NewEvents(Poll)
MainEventsCleared
RedrawEventsCleared
NewEvents(Poll)
MainEventsCleared
RedrawRequested(WindowId(WindowId(0xb0780)))
RedrawEventsCleared
NewEvents(Poll)
MainEventsCleared
RedrawEventsCleared
NewEvents(Poll)
MainEventsCleared
RedrawRequested(WindowId(WindowId(0xb0780)))
RedrawEventsCleared
```

`RedrawRequested` is dispatched every second iteration.

**Comment by filnet** [comment]
@Osspial may be we should first merge my PR and then you could try your new approach on top of it. My PR addresses the same issues as yours but is 100% in line with the current code/approach. No revolution there.

If we do that then we get a more stable version of winit on Windows out now and you can then work on the new approach without pressure.

PS: my PR still needs to be reviewed though ;)

**Comment by Osspial** [comment]
> @Osspial may be we should first merge my PR and then you could try your new approach on top of it. My PR addresses the same issues as yours but is 100% in line with the current code/approach. No revolution there.

That sounds like a good approach. I'll try to get your PR, and a bunch of the other Windows PRs that have been waiting on the backburner, reviewed later today.

**Comment by Osspial** [comment]
@filnet Would you be able to re-test this? I'm pretty sure I've fixed the bugs you brought up in your comments.

File: src/platform_impl/windows/event_loop.rs [hunk 1]
```diff
@@ -667,15 +751,34 @@ unsafe extern "system" fn public_window_callback<T: 'static>(
...
             drop(subclass_input);
             Box::from_raw(subclass_input_ptr as *mut SubclassInput<T>);
             0
         }
 
         winuser::WM_PAINT => {
-            subclass_input.event_loop_runner.main_events_cleared();
-            subclass_input.send_event(Event::RedrawRequested(RootWindowId(WindowId(window))));
+            if subclass_input.event_loop_runner.should_buffer() {
+                panic!("InvalidateRgn should be used instead of UpdateWindow");
```
Comment (filnet) [inline src/platform_impl/windows/event_loop.rs]: we should never panic in a Windows callback as it will cause Rust to unwind into foreign code which is undefined behavior

File: src/platform_impl/windows/event_loop.rs [hunk 2]
```diff
@@ -1707,65 +1817,21 @@ unsafe extern "system" fn thread_event_target_callback<T: 'static>(
...
-                        }
-                    }
-                }
+            // If the WM_PAINT handler in `public_window_callback` has already flushed the redraw
+            // events, `handling_events` will return false and we won't emit a second
+            // `RedrawEventsCleared` event.
+            if subclass_input.event_loop_runner.handling_events() {
+                // This WM_PAINT handler will never be re-entrant because `flush_paint_messages`
+                // doesn't call WM_PAINT for the thread event target (i.e. this window).
+                assert!(flush_paint_messages(
```
Comment (filnet) [inline src/platform_impl/windows/event_loop.rs]: smae, we should assert in a callback

File: src/platform_impl/windows/event_loop/runner.rs [hunk 3]
```diff
@@ -1,51 +1,50 @@
...
-    redraw_buffer: Rc<RefCell<VecDeque<WindowId>>>,
+    thread_msg_target: HWND,
+    wait_thread_id: DWORD,
+    processing_events: Cell<ProcessingEvents>,
+    panic_error: Cell<Option<PanicError>>,
+    control_flow: Cell<ControlFlow>,
+    last_events_cleared: Cell<Instant>,
+    event_handler: Cell<Option<Box<dyn FnMut(Event<'_, T>, &mut ControlFlow)>>>,
+    event_buffer: RefCell<VecDeque<BufferedEvent<T>>>,
+    owned_windows: Cell<HashSet<HWND>>,
```
Comment (filnet) [inline src/platform_impl/windows/event_loop/runner.rs]: EventLoopRunner has quite a bit more state than before. Compare it to my PR:
```
struct EventLoopRunner<T: 'static> {
    control_flow: ControlFlow,
    runner_state: RunnerState,
    modal_redraw_window: HWND,
    in_modal_loop: bool,
    event_handler: Box<dyn FnMut(Event<'_, T>, &mut ControlFlow)>,
    panic_error: Option<PanicError>,
}
```

File: src/platform_impl/windows/event_loop/runner.rs [hunk 4]
```diff
@@ -1,51 +1,50 @@
...
-    ScaleFactorChanged(WindowId, f64, PhysicalSize<u32>),
-}
-
-#[must_use]
-#[derive(Debug, Clone, Copy)]
-pub enum AreEventsBuffered {
-    EventsBuffered,
-    ReadyToSleep,
+#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
+enum ProcessingEvents {
```
Comment (filnet) [inline src/platform_impl/windows/event_loop/runner.rs]: the enum seems to duplicate the runner states and the name does not "speak" much an

**Comment by filnet** [comment]
Retested the same use cases and it looks fine.
But looking at the PR I don't think the architecture is that simpler.
There are now threads involved and the EventLoopRunner has much more state.

**Comment by filnet** [comment]
More testing shows that there might still be an issue with WaitUntil control flow.
Moving the mouse over the window will stop the loop until resized.

**Comment by filnet** [comment]
Changing the wait time in control_flow from 100ms to (1000 / 60)ms reproduces the issue.

You need to switch to WaitUntil control flow (by pressing '2'). Then move the mouse out of the window and back in. You should see that you then only get WindowEvent or DeviceEvent.
Strangely when in that state you can't close the window anymore (either with X button or Alt+F4).

Resizing the window will either restore the event loop to a working state or emit a LoopDestroyed event (!?!).

File: src/platform_impl/windows/event_loop/runner.rs (hunk 4 above)
Comment (Osspial) [reply src/platform_impl/windows/event_loop/runner.rs]: That's a good point - honestly, I'm not entirely sure why I renamed these fields 😅. I've gone ahead and reverted the names to `RunnerState`'s names.

File: src/platform_impl/windows/event_loop/runner.rs (hunk 3 above)
Comment (Osspial) [reply src/platform_impl/windows/event_loop/runner.rs]: I don't think that's a fair comparison. This PR introduces a few more fields, but the actual state management code has been simplified considerably; compare the [old state code](https://github.com/filnet/winit/blob/f346b43bd2f1f5292fc9d42ac5154afce2c9c1ae/src/platform_impl/windows/event_loop/runner.rs#L261-L455), which contains *several* nested match statements and is spread out over multiple functions, with the [new state code](https://github.com/filnet/winit/blob/f346b43bd2f1f5292fc9d42ac5154afce2c9c1ae/src/platform_impl/windows/event_loop/runner.rs#L261-L455), which concentrates all the state transition code into a single, more easily understandable function.

**Comment by Osspial** [comment]
> But looking at the PR I don't think the architecture is that simpler.
> There are now threads involved and the EventLoopRunner has much more state.

I'll admit that the secondary thread introduces a bit more complexity to the implementation, but there are a couple technical reasons that justify its inclusion:
- Using a secondary thread for the wait timer allows Winit to play much more nicely with externally driven event loops. Because we're using a secondary thread instead of `wait_until_time_or_msg`, the thread message window's `WM_PAINT` handler can return immediately instead of blocking until a new event gets received. This reduces the chance for weird bugs if the user calls one of win32's many modal functions while running Winit's event loop, or wants to run Winit as a plugin event loop in an external application (which isn't possible now, but [has been requested](https://github.com/rust-windowing/winit/issues/159#issuecomment-511124405) and should be attainable with this PR's work).
- This PR flushes all of Winit's `WM_PAINT` messages in the first `WM_PAINT` message received by the event loop, even if that message was delivered to a user-facing window rather than the thread event target window. We can't use `wait_until_time_or_msg` there, since doing so would prevent `WM_PAINT` from returning until the next event gets received and would delay displaying the redraw to the user.

> You need to switch to WaitUntil control flow (by pressing '2'). Then move the mouse out of the window and back in. You should see that you then only get WindowEvent or DeviceEvent.
> Strangely when in that state you can't close the window anymore (either with X button or Alt+F4).

That's... certainly bizarre! It'll take a bit to figure out why exactly that happens, since this doesn't seem like a bug with a simple, obvious fix.

**Comment by Osspial** [comment]
Alright, I fixed it! It was caused by a bug in `PeekMessageW`, and the bug was triggered by [this call](https://github.com/Osspial/winit/blob/67aab8c05843cab19ec542073ec9e359e1668365/src/platform_impl/windows/event_loop.rs#L2023). `PeekMessageW` with `PM_NOREMOVE` (which is `0`) set isn't supposed to remove messages from the event queue, but for whatever reason it was removing `WM_PAINT` from the queue when that paint message was triggered by a `RedrawWindow` call with the `RDW_INTERNALPAINT` flag set. Fixing it was just a matter of re-queuing the `WM_PAINT` message whenever an internal paint message was received.

File: src/platform_impl/windows/event_loop.rs (hunk 1 above)
Comment (Osspial) [reply src/platform_impl/windows/event_loop.rs]: Good catch! I've wrapped the entire match block in a `catch_unwind` call, so we shouldn't have to worry about this any more.

**Comment by filnet** [comment]
> 
> 
> Alright, I fixed it! It was caused by a bug in `PeekMessageW`, and the bug was triggered by [this call](https://github.com/Osspial/winit/blob/67aab8c05843cab19ec542073ec9e359e1668365/src/platform_impl/windows/event_loop.rs#L2023). `PeekMessageW` with `PM_NOREMOVE` (which is `0`) set isn't supposed to remove messages from the event queue, but for whatever reason it was removing `WM_PAINT` from the queue when that paint message was triggered by a `RedrawWindow` call with the `RDW_INTERNALPAINT` flag set. Fixing it was just a matter of re-queuing the `WM_PAINT` message whenever an internal paint message was received.

It is not a bug in P . The [documentaion](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-peekmessagew) mentions it:

> The PeekMessage function normally does not remove WM_PAINT messages from the queue. WM_PAINT messages remain in the queue until they are processed. However, if a WM_PAINT message has a NULL update region, PeekMessage does remove it from the queue.

File: src/platform_impl/windows/event_loop.rs [hunk 5]
```diff
@@ -1937,6 +2037,49 @@ unsafe extern "system" fn thread_event_target_callback<T: 'static>(
...
+
+            // if the control_flow is WaitUntil, make sure the given moment has actually passed
+            // before emitting NewEvents
+            if let ControlFlow::WaitUntil(wait_until) =
+                subclass_input.event_loop_runner.control_flow()
+            {
+                let mut msg = mem::zeroed();
+                while Instant::now() < wait_until {
+                    if 0 != winuser::PeekMessageW(&mut msg, ptr::null_mut(), 0, 0, 0) {
+                        // This works around a bug in PeekMessageW. If the message PeekMessageW
```
Comment (filnet) [inline src/platform_impl/windows/event_loop.rs]: This is not a bug in `PeekMessageW` but a documented feature.

File: src/platform_impl/windows/event_loop/runner.rs (hunk 3 above)
Comment (filnet) [reply src/platform_impl/windows/event_loop/runner.rs]: On the other hand you removed EventLoopRunner which had some state too (?).

File: src/platform_impl/windows/event_loop.rs (hunk 5 above)
Comment (Osspial) [reply src/platform_impl/windows/event_loop.rs]: Ah, right, I almost forgot - the Windows API has no bugs. Every exhibited behavior is a feature and will remain consistent until the end of time.

Comment (filnet) [reply src/platform_impl/windows/event_loop.rs]: Some of those APIs probably date back from Windows 3.1.

File: src/platform_impl/windows/event_loop/runner.rs (hunk 3 above)
Comment (Osspial) [reply src/platform_impl/windows/event_loop/runner.rs]: I've flattened out `EventLoopRunner` and `ELRShared` into a single struct. Thinking about it, we should probably the new `ELRShared` to `EventLoopRunner`, since the only real reason the `ELRShared` name exists was to distinguish between it and the normal `EventLoopRunner`.

Comment (filnet) [reply src/platform_impl/windows/event_loop/runner.rs]: Renaming `ELRShared` to `EventLoopRunner` sounds good.

**Comment by filnet** [comment]
I'll do a more in depth review this week (with an eye for pre 0.20.0 multithreaded left overs).

One thing I'd like to confirm is if we can get rid of the `InvalidateRgn` calls. Earlier tests in my branch showed the they are not necessary. The 'SetWindowPos` calls they follow already send the required messages.

**Comment by filnet** [comment]
Found an issue: in WaitUntil control flow the event loop will not start until a first event happens.

**Comment by filnet** [comment]
About the `WaitUntil` issue: it is possible to reproduce it with the control_flow example.

We first need to merge this pull request : https://github.com/rust-windowing/winit/pull/1511

Then if you change the example to start in `WaitUntil` mode and change the wait time to zero.

```
-const WAIT_TIME: time::Duration = time::Duration::from_millis(100);
+const WAIT_TIME: time::Duration = time::Duration::from_millis(0);
...
-    let mut mode = Mode::Wait;
+    let mut mode = Mode::WaitUntil;
```

With those changes, the event loop does not start. Seems like WaitUntil with an expired time is not well handled.

**Comment by Dooskington** [comment]
Any update on this? I was planning on using `winit` for the upcoming Ludum Dare jam but some Windows specific winit issues might prevent that. If there is any blocking work that needs to be looked at, let me know, I am willing to contribute :)

**Comment by notviri** [comment]
Seconding this, looks like the fix was implemented a month ago but never merged? Were there some unforeseen side effects of this fix? Can help out too if possible.

**Comment by filnet** [comment]
This branch still has an issue with `WaitUntil` control flow.

But note that most crashes fixed by this branch are also fixed in version 0.22.0.
This branch does fix one issue outstanding in master that affects Poll control flow and calling `request_redraw`. If you don't need that then you are safe to use 0.22.0.

See https://github.com/rust-windowing/winit/issues/1522 and https://github.com/rust-windowing/winit/issues/1477.

**Comment by notviri** [comment]
Yes, unfortunately that hanging problem is the issue I'm having too as I use `Poll` & `request_redraw` in my app. I guess I'll use this fix branch for now.

**Comment by Osspial** [comment]
Alright, I've figured out how to fix the issue that made #1484 worse. I've tested the `control_flow` example and everything seems to be working fine. @filnet could you do a quick pass over this to double-check it's working properly? Assuming nothing comes up, this should be good to merge.

**Comment by filnet** [comment]
> 
> 
> Alright, I've figured out how to fix the issue that made #1484 worse. I've tested the `control_flow` example and everything seems to be working fine. @filnet could you do a quick pass over this to double-check it's working properly? Assuming nothing comes up, this should be good to merge.

Will test that branch this weekend.

**Comment by filnet** [comment]
Quickly tested all control flow modes with and without calling `request_redraw` (using the control_flow example).
Looks good to me.
