### PR TITLE
Filter out tiny mouse events

### LINKED ISSUE #3500: X11: Mouse motion events sometimes contain garbage
While printing out events on X11, I noticed that sometimes (not always), the motion events are invalid:
```
DeviceEvent { device_id: DeviceId(X(DeviceId(2))), event: Motion { axis: 0, value: -1.0 } }
DeviceEvent { device_id: DeviceId(X(DeviceId(2))), event: Motion { axis: 1, value: 7.1e-322 } }
DeviceEvent { device_id: DeviceId(X(DeviceId(2))), event: MouseMotion { delta: (-1.0, 7.1e-322) } }
```
Only one axis gets reported and the second axis is just an unrelated value (most likely smth not belonging to the event).
```
for i in 0..xev.valuators.mask_len * 8 {
    if !xinput2::XIMaskIsSet(mask, i) {
        continue;
    }
    let x = unsafe { *value };
```

The easiest way I found to reproduce this is just moving the cursor between two monitors. It might also just be a x11 problem.

I'm running natively latest Arch Linux with Gnome using X11.

### PR DESCRIPTION
**Pull request by notgull**
Usually, if mouse events are equal to (0, 0) we filter them out.
However, if the event is very close to zero it will still be given to
the user. In some cases this can be caused by bad float math on the X11
server side.

I fix this by refusing to forward events where both of their deltas fall
below a certain threshold.

Closes #3500

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

File: src/platform_impl/linux/x11/event_processor.rs [hunk 1]
```diff
@@ -41,6 +41,9 @@ use crate::platform_impl::x11::{
 /// The X11 documentation states: "Keycodes lie in the inclusive range `[8, 255]`".
 const KEYCODE_OFFSET: u8 = 8;
 
+/// Minimum delta for a device event to be considered.
+const NOTGULL_THRESHOLD: f32 = 4.0e-8;
```
Comment (madsmtm) [inline src/platform_impl/linux/x11/event_processor.rs:45]: I should insert my username in more source code! 😁

(I've tried hard with the `mtm: MainThreadMarker`, but while `mtm` is my initials, nothing beats just spelling out the whole thing)

**Review by madsmtm — APPROVED** [review]

File: src/platform_impl/linux/x11/event_processor.rs (hunk 1 above)
Comment (kchibisov) [reply src/platform_impl/linux/x11/event_processor.rs:45]: Should be renamed to something useful. Also it should be explained why the given constant was picked in the first place, otherwise it _may_ not work for some cases.

There's also a case where you move the mouse really slowly, thus filtering may not actually move the mouse where it should or accumulate in error.

File: src/platform_impl/linux/x11/event_processor.rs [hunk 2]
```diff
@@ -1464,15 +1467,17 @@ impl EventProcessor {
             value = unsafe { value.offset(1) };
         }
 
-        if mouse_delta != (0.0, 0.0) {
+        if mouse_delta.0.abs() as f32 >= NOTGULL_THRESHOLD
+            || mouse_delta.1.abs() as f32 >= NOTGULL_THRESHOLD
```
Comment (kchibisov) [inline src/platform_impl/linux/x11/event_processor.rs:1471]: I don't quite like this logic in-particular. Could you instead check if the given value is small enough and null it? Then just send the thing if something is not null, since those low values don't make much sense in the first place.

**Review by kchibisov — CHANGES_REQUESTED** [review]

**Comment by valaphee** [comment]
This wouldn't fix the underlying issue. Interestingly, I didn't had any issues with Bevy for example, but its also not a regression.

Didn't use thresholds because normally raw mouse input events should not be less than 1.0

**Comment by notgull** [comment]
> This wouldn't fix the underlying issue. Interestingly, I didn't had any issues with Bevy for example, but its also not a regression.
> 
> Didn't want to use thresholds because normally raw mouse input events should not be less than 1.0

I think the underlying issue is that the underlying driver is making an error somewhere in the floating point calculation and sending us a very tiny number instead of zero. `7.1e-222` is far less than the epsilon on all platforms, so for all intents and purposes it might as well be zero.

File: src/platform_impl/linux/x11/event_processor.rs (hunk 1 above)
Comment (notgull) [reply src/platform_impl/linux/x11/event_processor.rs]: I've elected to use the float epsilon instead. Since float comparison breaks down past the epsilon, for all intentions and purposes any number less than the epsilon is zero.

**Comment by valaphee** [comment]
Then this would definitely be a valid fix, but the value is always near zero, even if there is movement

File: src/platform_impl/linux/x11/event_processor.rs [hunk 3]
```diff
@@ -1889,6 +1889,59 @@ impl EventProcessor {
     }
 }
 
+/// Recorded mouse delta designed to filter out noise.
+struct Delta<T> {
+    inner: Option<(T, T)>,
+}
```
Comment (kchibisov) [inline src/platform_impl/linux/x11/event_processor.rs:1895]: Put it somewhere else, we have entire directly with called `util`(the most useless name for directly btw) just laying around for stuff like that.

**Review by kchibisov — CHANGES_REQUESTED** [review]

**Comment by notgull** [comment]
> Then this would definitely be a valid fix, but the value is always near zero, even if there is movement, that's why I don't think it's a floating point error.

My understanding of Xinput's raw mouse events is that they are always multiples of 1. So we shouldn't be seeing any floating point numbers anyways. So it's fine for us to assume that a value less than the epsilon is, for all intents and purposes, supposed to be zero.

File: src/platform_impl/linux/x11/event_processor.rs [hunk 4]
```diff
@@ -1889,6 +1889,59 @@ impl EventProcessor {
     }
 }
 
+/// Recorded mouse delta designed to filter out noise.
+struct Delta<T> {
+    inner: Option<(T, T)>,
```
[the remark this answers is not in the document]
Comment (notgull) [reply src/platform_impl/linux/x11/event_processor.rs]: Good point, fixed

File: src/platform_impl/linux/x11/event_processor.rs (hunk 3 above)
Comment (notgull) [reply src/platform_impl/linux/x11/event_processor.rs]: Moved to `util/mouse.rs`

File: src/platform_impl/linux/x11/event_processor.rs [hunk 5]
```diff
@@ -1464,15 +1464,15 @@ impl EventProcessor {
...
+        if let Some(mouse_delta) = mouse_delta.consume() {
             let event = Event::DeviceEvent {
                 device_id: did,
                 event: DeviceEvent::MouseMotion { delta: mouse_delta },
             };
             callback(&self.target, event);
         }
 
-        if scroll_delta != (0.0, 0.0) {
+        if let Some(scroll_delta) = scroll_delta.consume() {
```
[the remark this answers is not in the document]
Comment (notgull) [reply src/platform_impl/linux/x11/event_processor.rs:1475]: Good point, fixed

**Review by kchibisov — APPROVED** [review]

File: src/platform_impl/linux/x11/util/mouse.rs [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+    }
+}
+
+macro_rules! consume {
+    ($this:expr, $ty:ty) => {{
+        let this = $this;
+        let (x, y) = match (this.x.abs() < <$ty>::EPSILON, this.y.abs() < <$ty>::EPSILON) {
+            (true, true) => return None,
+            (true, false) => (this.x, 0.0),
+            (false, true) => (0.0, this.y),
```
Comment (irate-devil) [inline src/platform_impl/linux/x11/util/mouse.rs:34]: Hey yall :) The code here is mistakenly returning the axis that's lower than the epsilon.
It's the likely cause of this issue in Bevy: https://github.com/bevyengine/bevy/issues/12198.
```suggestion
            (false, true) => (this.x, 0.0),
            (true, false) => (0.0, this.y),
```
