### PR TITLE
Preserve with_maximized on windows

### LINKED ISSUE #1510: WindowBuilder::with_maximized does not work on Windows
Version: 0.22.0
Backend: Windows

Steps to reproduce:

1) Checkout the `v0.22.0` git tag
2) Modify `examples/window.rs` to do `WindowBuilder::with_maximized(true)` instead of `with_inner_size`
3) Observe the non-maximized window

Note that `Window::set_maximized` still works. Also other platforms I tested (X11 and macOS) seem to work.

I am willing to contribute a fix you'll have the patience with me 😄

### PR DESCRIPTION
**Pull request by yanchith**
Closes #1510 

~On Windows, to prevent the MAXIMIZED flag from being overwritten, this only calls `Window::set_inner_size` if not MAXIMIZED or explicit window size was provided. If both `WindowBuilder::with_maximized(true)` and `WindowBuilder::with_inner_size(...)` are provided, `inner_size` will win over MAXIMIZED.~

Update: see https://github.com/rust-windowing/winit/pull/1515#issuecomment-602501576

- [X] Tested on all platforms changed
- [X] Compilation warnings were addressed
- [X] `cargo fmt` has been run on this branch
- [X] `cargo doc` builds successfully
- [X] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by yanchith** [comment]
Now takes https://github.com/rust-windowing/winit/issues/1510#issuecomment-602495355 into account

File: src/platform_impl/windows/window.rs [hunk 1]
```diff
@@ -758,6 +756,11 @@ unsafe fn init<T: 'static>(
         .unwrap_or_else(|| PhysicalSize::new(1024, 768).into());
     win.set_inner_size(dimensions);
     win.set_visible(attributes.visible);
```
Comment (filnet) [inline src/platform_impl/windows/window.rs]: would probably make sense to call `set_visible` after `set_maximized` ?

**Comment by Osspial** [comment]
LGTM. Will merge once CI finishes. Thanks for fixing this!
