### PR TITLE
Properly interpret float data in drag ops

### LINKED ISSUE #3245: Example `window_drag_resize` crashing on Ubuntu with X11
I cloned the latest master branch of the winit repo and ran the `window_drag_resize` example like so...

```sh
cargo run --example window_drag_resize | grep -E '(INFO|WARN|ERROR)'
```

Dragging and resizing are moving/resizing the window incorrectly, and eventually crashes with enough interactions. (Apologies for the poor quality of recording. Screen recording isn't working on my system.)

bug

Enabling the native window decorations and using that works as expected, but using the custom-built functionality in the example causes those issues. Here is the logs from that example:

```
RUST_BACKTRACE=1 cargo run --example window_drag_resize | grep -E '(INFO|WARN|ERROR)'
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/window_drag_resize`
INFO  [winit::platform_impl::platform::x11::window] Guessed window scale factor: 2.4166666666666665
Press 'B' to toggle borderless
thread 'main' panicked at src/platform_impl/linux/x11/window.rs:1742:21:
attempt to add with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: winit::platform_impl::platform::x11::window::UnownedWindow::drag_initiate
             at ./src/platform_impl/linux/x11/window.rs:1742:21
   4: winit::platform_impl::platform::x11::window::UnownedWindow::drag_resize_window
             at ./src/platform_impl/linux/x11/window.rs:1692:9
   5: winit::platform_impl::platform::Window::drag_resize_window
             at ./src/platform_impl/linux/mod.rs:444:55
   6: winit::window::Window::drag_resize_window::{{closure}}
             at ./src/window.rs:1440:37
   7: winit::platform_impl::platform::Window::maybe_wait_on_main
             at ./src/platform_impl/linux/mod.rs:314:9
   8: winit::window::Window::drag_resize_window
             at ./src/window.rs:1439:9
   9: window_drag_resize::main::{{closure}}
             at ./examples/window_drag_resize.rs:54:32
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:294:13
  11: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:294:13
  12: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}
             at ./src/platform_impl/linux/x11/mod.rs:638:21
  13: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
             at ./src/platform_impl/linux/x11/event_processor.rs:734:45
  14: winit::platform_impl::platform::x11::EventLoop<T>::drain_events
             at ./src/platform_impl/linux/x11/mod.rs:630:13
  15: winit::platform_impl::platform::x11::EventLoop<T>::single_iteration
             at ./src/platform_impl/linux/x11/mod.rs:559:9
  16: winit::platform_impl::platform::x11::EventLoop<T>::poll_events_with_timeout
             at ./src/platform_impl/linux/x11/mod.rs:543:9
  17: winit::platform_impl::platform::x11::EventLoop<T>::pump_events
             at ./src/platform_impl/linux/x11/mod.rs:449:13
  18: winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand
             at ./src/platform_impl/linux/x11/mod.rs:410:19
  19: winit::platform_impl::platform::EventLoop<T>::run_on_demand
             at ./src/platform_impl/linux/mod.rs:821:56
  20: winit::platform_impl::platform::EventLoop<T>::run
             at ./src/platform_impl/linux/mod.rs:814:9
  21: winit::event_loop::EventLoop<T>::run
             at ./src/event_loop.rs:249:9
  22: window_drag_resize::main
             at ./examples/window_drag_resize.rs:30:5
  23: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

My system is running the latest Ubuntu 22.04 on X11 with the default GNOME config.
This exact same issue also happens if I use Wayland, but force the use of Xwayland using `WAYLAND_DISPLAY=""`.
On native Wayland it works just fine.

## Some System Info

```sh
env | grep -iE '(xdg|x11|wayland|display)'
```
```
XDG_SESSION_TYPE=x11
XDG_SESSION_CLASS=user
XDG_RUNTIME_DIR=/run/user/1000
XDG_MENU_PREFIX=gnome-
DISPLAY=:0
XDG_CURRENT_DESKTOP=Unity
XDG_SESSION_DESKTOP=ubuntu-xorg
XDG_DATA_DIRS=/usr/share/ubuntu-xorg:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu-xorg:/etc/xdg
ORIGINAL_XDG_CURRENT_DESKTOP=ubuntu:GNOME
GDK_BACKEND=x11
```

```
uname -a
Linux queenie 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

```
gnome-shell --version
GNOME Shell 42.9
```

I tried varying the scale factor in GNOME settings (100%, 200%, and 300%) and the same thing happens regardless of scale factor, though the "Guessed window scale factor" is still `2.4166666666666665` in all cases

Screenshot from 2023-11-27 13-20-13

### PR DESCRIPTION
**Pull request by notgull**
Closes #3245

notgull forgot to properly interpret float data from the X server, making him tonight's biggest loser.

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

File: src/platform_impl/linux/x11/mod.rs [hunk 1]
```diff
@@ -1128,3 +1128,9 @@ impl Device {
         }
     }
 }
+
+/// Convert the raw X11 representation for a 32-bit floating point to a double.
+#[inline]
+fn xinput_fp1616_to_float(fp: xinput::Fp1616) -> f64 {
+    (fp as f64) / ((1 << 16) as f64)
```
Comment (kchibisov) [inline src/platform_impl/linux/x11/mod.rs:1135]: That looks like should be a part of x11rb?

Comment (notgull) [reply src/platform_impl/linux/x11/mod.rs:1135]: I don't know. `x11rb` mostly deals with fetching and retrieving data from the server and not interpreting it.

@psychon Thoughts on this?

Comment (notgull) [reply src/platform_impl/linux/x11/mod.rs:1135]: Either way it will probably be a while before the next `x11rb` release, so to fix this bug let's just include it here.

**Review by kchibisov — APPROVED** [review]

File: src/platform_impl/linux/x11/mod.rs (hunk 1 above)
Comment (psychon) [reply src/platform_impl/linux/x11/mod.rs:1135]: > @psychon Thoughts on this?

"xcb doesn't provide something like this either", but that's no good reason. x11rb also provides extra helper functions on `GetPropertyReply` like `value8()`, so we could also add `Fp1616::as_f64()` (suggestions for a name welcome). The property code seems to be done in `generator/src/generator/special_cases.rs`. So... feel free to open a PR for adding this case. Seems relatively simple and straight-forward.
