### PR TITLE
macOS: Support click-dragging out of a window

### LINKED ISSUE #1599: [macos] Click-dragging out of a window doesn't work on macOS
How to reproduce:
- run "control_flow" example on macOS
- press LMB inside the window area
- move the cursor outside of a window.

Expected: CursorMoved events keep coming
Real: CursorMoved disappear when the cursor leaves a window area

It works fine on Windows and Linux (checked on X11), but not on macOS.

### PR DESCRIPTION
**Pull request by ozkriff**
This is my naive attempt to fix #1599. It seems to work, though I've only checked on a remote macOS machine.

Fixes #1599 (_"[macos] Click-dragging out of a window doesn't work on macOS"_) 
Related to #292 (_"Add mouse event capturing when click-dragging out of a win32 window"_)

### CODE REVIEW

**Comment by vitvakatu** [comment]
I can confirm the fix is working on native macOS Catalina

**Comment by ozkriff** [comment]
Not sure why the "CI / Tests (stable, x86_64-apple-ios, macos-latest) (pull_request)" job was auto-canceled. I don't have the access to restart it.

File: src/platform_impl/macos/view.rs [hunk 1]
```diff
@@ -77,6 +78,7 @@ pub fn new_view(ns_window: id) -> (IdRef, Weak<Mutex<CursorState>>) {
         is_key_down: false,
         modifiers: Default::default(),
         tracking_rect: None,
+        mouse_buttons_down: 0,
```
Comment (chrisduerr) [inline src/platform_impl/macos/view.rs:81]: Mouse events provide the `pressedMouseButtons` field. Have you considered using that instead of implementing tracking yourself?

**Comment by ozkriff** [comment]
@chrisduerr yeah, pressedMouseButtons seems to work fine, thanks. Updated the PR.

File: src/platform_impl/macos/view.rs [hunk 2]
```diff
@@ -910,13 +910,17 @@ fn mouse_motion(this: &Object, event: id) {
         let view_point = view.convertPoint_fromView_(window_point, nil);
         let view_rect = NSView::frame(view);
 
+        let mouse_buttons_down: NSInteger = msg_send![class!(NSEvent), pressedMouseButtons];
```
Comment (chrisduerr) [inline src/platform_impl/macos/view.rs:913]: Why put this outside of the conditional? Seems like a waste to do this when you don't need to?

Comment (chrisduerr) [reply src/platform_impl/macos/view.rs:913]: You can of course keep this outside and just add `|| mouse_button_down == 0`, which would reduce the level of nesting. Perhaps that was the original intention of putting it here?

Comment (ozkriff) [reply src/platform_impl/macos/view.rs]: Moved the variable inside the if body.

It's possible to merge both conditions, but the result is (subjectively) harder to read because of all the brackets.

Comment (chrisduerr) [reply src/platform_impl/macos/view.rs]: Since there's also no clean way to inline the msg_send! directly, meaning that this variation also has a slight performance advantage in the general case of sending events, I agree that it's the best choice.
