### PR TITLE
Ignore mutex poisoning in X11_BACKEND

### LINKED ISSUE #3870: X11_BACKEND.lock() fails
### Description

When I try to run the last version of lapce, I get:
```
thread main panicked at <unknown> | file://.//usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-winit-0.29.4/src/platform_impl/linux/mod.rs:787:62
   0: lapce_app::app::logging::panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: floem_winit::platform_impl::platform::EventLoop<T>::new
   8: lapce_app::app::launch
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: main
  11: <unknown>
  12: __libc_start_main
  13: _start
```

The unwrap in question is that one behind `X11_BACKEND.lock()`. Any idea why this happens?

### OS and window mananger

Debian testing i386/qemu, mate desktop, x11

### Winit version

0.29.4

### PR DESCRIPTION
**Pull request by notgull**
A panic doesn't really put any of the fields in XConnection into an invalid
state, so there is no real reason to panic when poisoning is detected.
So just ignore the poison.

Closes #3870

- [ ] Tested on all platforms changed
- [x] Added an entry to the `changelog` module if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Review by kchibisov — APPROVED** [review]

File: src/platform_impl/linux/mod.rs [hunk 1]
```diff
@@ -626,7 +626,7 @@ unsafe extern "C" fn x_error_callback(
     display: *mut x11::ffi::Display,
     event: *mut x11::ffi::XErrorEvent,
 ) -> c_int {
-    let xconn_lock = X11_BACKEND.lock().unwrap();
+    let xconn_lock = X11_BACKEND.lock().unwrap_or_else(|e| e.into_inner());
```
Comment (daxpedda) [inline src/platform_impl/linux/mod.rs:629]: I usually prefer:
```suggestion
    let xconn_lock = X11_BACKEND.lock().unwrap_or_else(PoisonError::into_inner);
```
Purely a preference thing.

**Review by daxpedda — APPROVED** [review]

File: src/platform_impl/linux/mod.rs (hunk 1 above)
Comment (notgull) [reply src/platform_impl/linux/mod.rs:629]: I don't like the verbosity here.

**Comment by L3P3** [comment]
Any idea why this error could occur? Do I understand correctly that mutex poisoning might only happen if another thread panics? Why would we handle panics this way instead of handling the panic itself (I have not seen any other panic before)?

**Comment by kchibisov** [comment]
The thread is running outside of the winit itself, since winit doesn't spawn any threads at all, so where it happens is not our responsibility.
