### PR TITLE
Remove assertions from Windows dark mode code

### LINKED ISSUE #1405: [Windows] unable to run example (panicked at 'assertion failed: `(left == right)` left: `1`, right: `0`)
Unable to run window example on Windows 10. (Windows Settings -> Personalization -> colors=Light).

cargo run --example window

```
Finished dev [unoptimized + debuginfo] target(s) in 0.23s
Running `target\debug\examples\window.exe`
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `1`,
right: `0`', src\platform_impl\windows\dark_mode.rs:135:13
stack backtrace:
0:     0x7ff6b813a189 - backtrace::backtrace::trace_unsynchronized
at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
1:     0x7ff6b813a189 - std::sys_common::backtrace::_print_fmt 
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:77
2:     0x7ff6b813a189 - std::sys_common::backtrace::_print::{{impl}}::fmt
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:61
3:     0x7ff6b814ea6b - core::fmt::write
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\fmt\mod.rs:1028
4:     0x7ff6b81377e4 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\io\mod.rs:1412
5:     0x7ff6b813c929 - std::sys_common::backtrace::_print
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:65
6:     0x7ff6b813c929 - std::sys_common::backtrace::print
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:50
7:     0x7ff6b813c929 - std::panicking::default_hook::{{closure}}
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:188
8:     0x7ff6b813c57c - std::panicking::default_hook
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:205
9:     0x7ff6b813d17c - std::panicking::rust_panic_with_hook
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:464
10:     0x7ff6b813ccf0 - std::panicking::continue_panic_fmt
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:373
11:     0x7ff6b813cc34 - std::panicking::begin_panic_fmt
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:328
12:     0x7ff6b80dc7e8 - winit::platform_impl::platform::dark_mode::set_dark_mode_for_window
at E:\Projects\Rust\winit\src\platform_impl\windows\dark_mode.rs:135
13:     0x7ff6b80dc456 - winit::platform_impl::platform::dark_mode::try_dark_mode
at E:\Projects\Rust\winit\src\platform_impl\windows\dark_mode.rs:91
14:     0x7ff6b8083ddd - winit::platform_impl::platform::window::init<()>
at E:\Projects\Rust\winit\src\platform_impl\windows\window.rs:754
15:     0x7ff6b80848c8 - winit::platform_impl::platform::window::Window::new<()>
at E:\Projects\Rust\winit\src\platform_impl\windows\window.rs:72
16:     0x7ff6b807e6e4 - winit::window::WindowBuilder::build<()>
at E:\Projects\Rust\winit\src\window.rs:333
17:     0x7ff6b807c25e - window::main
at E:\Projects\Rust\winit\examples\window.rs:11
18:     0x7ff6b807a2f0 - std::rt::lang_start::{{closure}}<()>
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\rt.rs:61
19:     0x7ff6b813cb37 - std::rt::lang_start_internal::{{closure}}
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:48
20:     0x7ff6b813cb37 - std::panicking::try::do_call<closure-0,i32>
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:287
21:     0x7ff6b813faf2 - panic_unwind::__rust_maybe_catch_panic
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libpanic_unwind\lib.rs:78
22:     0x7ff6b813d4b2 - std::panicking::try
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:265
23:     0x7ff6b813d4b2 - std::panic::catch_unwind
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panic.rs:396
24:     0x7ff6b813d4b2 - std::rt::lang_start_internal
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\rt.rs:47
25:     0x7ff6b807a2cb - std::rt::lang_start<()>
at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libstd\rt.rs:61
26:     0x7ff6b807c3c0 - main
27:     0x7ff6b81529c4 - invoke_main
at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
28:     0x7ff6b81529c4 - __scrt_common_main_seh
at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
29:     0x7ffa93f77bd4 - BaseThreadInitThunk
30:     0x7ffa94ccce71 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\examples\window.exe` (exit code: 101)
```

### LINKED ISSUE #1458: Crashes on Windows 10 1809 10.0.17763.1
This was reported upstream in https://github.com/alacritty/alacritty/issues/3177.

It seems like on some Windows 10 systems, like Windows 10 Enterprise LTSC 1809, the new dark mode options are causing an assertion panic.

This assert is failing:
https://github.com/rust-windowing/winit/blob/83b60beba6ef53a10e3fa63eb0716372268ba199/src/platform_impl/windows/dark_mode.rs#L135-L138

### PR DESCRIPTION
**Pull request by chrisduerr**
In general, winit should never assert on anything unless it means that
it is impossible to continue the execution of the program. There are
several assertions in the Windows dark mode code where this is not the
case.

Based on surface level inspection, all existing assertions could be
easily replaced with just simple conditional checks, allowing the
execution of the program to proceed with sane default values.

Fixes #1458.
Fixes #1405.

### CODE REVIEW

File: src/platform_impl/windows/dark_mode.rs [hunk 1]
```diff
@@ -132,11 +124,12 @@ fn set_dark_mode_for_window(hwnd: HWND, is_dark_mode: bool) {
                 cbData: std::mem::size_of_val(&is_dark_mode_bigbool) as _,
             };
 
-            assert_eq!(
-                1,
-                set_window_composition_attribute(hwnd, &mut data as *mut _)
-            );
+            let status = set_window_composition_attribute(hwnd, &mut data as *mut _);
+
+            status == 0
```
Comment (daxpedda) [inline src/platform_impl/windows/dark_mode.rs]:
```suggestion
            status == 1
```
Actually it would also be nice to find out what is making this crash:
```suggestion
            match status {
                1 => true,
                error => {
                    log::error!("{}: {}", error, std::io::Error::last_os_error());
                    false
                }
            }
```

**Comment by daxpedda** [comment]
Fixes #1405 too.

I would like to know what the error actually is, @chrisduerr mentions in #1458 that it happens in Windows 10 Enterprise LTSC 1809, which I tried and can't reproduce.

So if someone can try using `std::io::Error::last_os_error()` as mentioned [above](https://github.com/rust-windowing/winit/pull/1459#discussion_r378839717) and report back it would be amazing.

**Comment by chrisduerr** [comment]
@daxpedda If you test `Windows 10 1809 10.0.17763.1`, you should be able to reproduce. It's not the latest version of Windows 10 1809.

File: src/platform_impl/windows/dark_mode.rs (hunk 1 above)
Comment (chrisduerr) [reply src/platform_impl/windows/dark_mode.rs]: Just a wild guess, but I'd assume the `WCA_USEDARKMODECOLORS` window compositing attribute is unknown. That's really the only thing that could fail here.

Comment (daxpedda) [reply src/platform_impl/windows/dark_mode.rs]: Yeah I assume so too, would be nice to know for sure though.
In any case, `0` is wrong, it should be `1`, accord to [this](https://www.undoc.airesoft.co.uk/user32.dll/SetWindowCompositionAttribute.php):
> Nonzero on success, zero otherwise. Call GetLastError on failure for more information.

Comment (chrisduerr) [reply src/platform_impl/windows/dark_mode.rs]: Oh yeah, my bad. I previously have returned a bool on `status == 0` here and have just changed the statement without inverting the assertion. Great catch.

Comment (chrisduerr) [reply src/platform_impl/windows/dark_mode.rs]: It should be `status != 0` though, not `status == 1`.

File: src/platform_impl/windows/dark_mode.rs [hunk 2]
```diff
@@ -132,11 +124,12 @@ fn set_dark_mode_for_window(hwnd: HWND, is_dark_mode: bool) {
                 cbData: std::mem::size_of_val(&is_dark_mode_bigbool) as _,
             };
 
-            assert_eq!(
-                1,
-                set_window_composition_attribute(hwnd, &mut data as *mut _)
-            );
+            let status = set_window_composition_attribute(hwnd, &mut data as *mut _);
+
+            status == 1
```
Comment (chrisduerr) [inline src/platform_impl/windows/dark_mode.rs]:
```suggestion
            status != 0
```

File: src/platform_impl/windows/dark_mode.rs (hunk 1 above)
Comment (daxpedda) [reply src/platform_impl/windows/dark_mode.rs]: Yeah the documentation is actually not accurate, the return type is [`BOOL`](https://docs.rs/winapi/0.3.8/winapi/shared/minwindef/type.BOOL.html), which can only be [`TRUE`](https://docs.rs/winapi/0.3.8/winapi/shared/minwindef/constant.TRUE.html)(1) or [`FALSE`](https://docs.rs/winapi/0.3.8/winapi/shared/minwindef/constant.FALSE.html)(0), we should actually check for that.

```suggestion
            status == TRUE
```
And also add `use winapi::shared::minwindef::{TRUE, FALSE};`

Comment (chrisduerr) [reply src/platform_impl/windows/dark_mode.rs]: I mean that's basically how booleans work, usually it's 1 for true and 0 for false, but all other values should also be treated as true. That's probably why the documentation states it that way, so checking for `!= 0` means you're on the safe side.

**Comment by chrisduerr** [comment]
@ryanisaacg Since you were so helpful with testing the modifier PR, could you check this too?

Since this is such a trivial change, it would be unfortunate if this didn't make it for the next release I think.

**Comment by ryanisaacg** [comment]
I'm not on the affected version of Windows, I think? I can run it and see if it works on my system though.

**Comment by Osspial** [comment]
@LaylConway mentioned that she was running into these panics in the Rust Discord, and this branch fixed the issues for her. I'll go ahead and merge this now. Sorry this was sitting on the backburner for so long!
