### PR TITLE
On X11, fix IME crashing without available styles

### LINKED ISSUE #2510: Failed to open fallback input method: ContextCreationFailed(Null)
### What happens
Restart fcitx5 cause Alacritty close.
### What should happen
Alacritty should not be closed.
### System
OS: Debian GNU/Linux bookworm/sid x86_64
Version: winit-0.27.3
Alacritty Version: alacritty 0.12.0-dev (e9ee8dc)
 cargo build with only X11 support
Display server: X11
Compositor: picom
WM: dwm
### How to reproduce the issue
I can post it again if needed, but probably not necessary.
https://github.com/alacritty/alacritty/issues/6370#issuecomment-1264634153

### PR DESCRIPTION
**Pull request by kchibisov**
Fixes #2510.

- [x] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

--

I can't repro the initial issue in the first place though and it doesn't make any sense, but it was bisected to the recent change.

### CODE REVIEW

File: src/platform_impl/linux/x11/ime/callbacks.rs [hunk 1]
```diff
@@ -108,10 +108,21 @@ unsafe fn replace_im(inner: *mut ImeInner) -> Result<(), ReplaceImError> {
...
+
+        // Check if the IME was allowed on that context.
+        let is_allowed = old_context
             .as_ref()
-            .map(|old_context| old_context.style)
+            .map(|old_context| old_context.is_allowed())
             .unwrap_or_default();
+
+        // We can't use the style from the old context here, since it may change on reload, so
+        // pick style from the nem xim based on the old state.
```
Comment (chrisduerr) [inline src/platform_impl/linux/x11/ime/callbacks.rs:119]:
```suggestion
        // pick style from the new XIM based on the old state.
```

**Review by chrisduerr — CHANGES_REQUESTED** [review]
Just a small typo.

**Comment by kchibisov** [comment]
Patch was tested here https://github.com/alacritty/alacritty/issues/6370#issuecomment-1272622150
