### PR TITLE
Use the right atom type in focus_window()

### LINKED ISSUE #3248: Window::focus_window method on X11 crashing, unreachable code
I'm calling the `winit::window::Window::focus_window` method on an X11 system. It crashes with `internal error: entered unreachable code`.

Here is a stack trace starting from the winit source:

```
thread 'main' panicked at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/x11/util/window_property.rs:119:18:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: <winit::platform_impl::platform::x11::util::window_property::PropIterator<x11rb::xcb_ffi::XCBConnection, u64>>::new
             at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/x11/util/window_property.rs:119:18
   4: <winit::platform_impl::platform::x11::xdisplay::XConnection>::get_property::<u64>
             at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/x11/util/window_property.rs:45:24
   5: <winit::platform_impl::platform::x11::window::UnownedWindow>::focus_window
             at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/x11/window.rs:1737:13
   6: <winit::platform_impl::platform::Window>::focus_window
             at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/mod.rs:539:50
   7: <winit::window::Window>::focus_window::{closure#0}
             at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/window.rs:1254:45
   8: <winit::platform_impl::platform::Window>::maybe_queue_on_main::<<winit::window::Window>::focus_window::{closure#0}>
             at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/mod.rs:310:9
   9: <winit::window::Window>::focus_window
             at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/window.rs:1254:9
```

## Some System Info

```sh
env | grep -iE '(xdg|x11|wayland|display)'
```
```
XDG_SESSION_TYPE=x11
XDG_SESSION_CLASS=user
XDG_RUNTIME_DIR=/run/user/1000
XDG_MENU_PREFIX=gnome-
DISPLAY=:0
XDG_CURRENT_DESKTOP=Unity
XDG_SESSION_DESKTOP=ubuntu-xorg
XDG_DATA_DIRS=/usr/share/ubuntu-xorg:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu-xorg:/etc/xdg
ORIGINAL_XDG_CURRENT_DESKTOP=ubuntu:GNOME
GDK_BACKEND=x11
```

```
uname -a
Linux queenie 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

```
gnome-shell --version
GNOME Shell 42.9
```

### PR DESCRIPTION
**Pull request by notgull**
Closes #3248 by removing an Xlibism I forgot about

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality
- [x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

File: src/platform_impl/linux/x11/window.rs [hunk 1]
```diff
@@ -1777,14 +1777,16 @@ impl UnownedWindow {
 
     #[inline]
     pub fn focus_window(&self) {
+        const ICONIC_STATE: u32 = 3;
```
Comment (kchibisov) [inline src/platform_impl/linux/x11/window.rs:1780]: Don't we have a common place to define such constants?

**Review by kchibisov — CHANGES_REQUESTED** [review]
changelog entry.

**Review by kchibisov — APPROVED** [review]
